apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rpqofzowt-dotnet-basic
  janus-idp.io/tekton: rpqofzowt-dotnet-basic
  backstage.io/kubernetes-id: rpqofzowt-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rpqofzowt-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
